[functions]
  external_node_modules = ["@prisma/client"]
[build]
  command = "npx prisma generate && npm run build"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://yonopedia.fjulian.me"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
